; Generated by AutoGUI 2.2.5a
#NoEnv
#SingleInstance Force
SetWorkingDir %A_ScriptDir%

Gui Add, Button, x157 y84 w0 h0, &OK
Gui Add, Button, x348 y248 w80 h23, &OK
Gui Add, Tab3, x22 y18 w408 h223, Configurações||Paragon|Perfil Auto 1|Perfil Auto 2|Perfil Auto 3|Perfil Auto 4|Perfil Auto 5|Perfil Auto 6|Perfil Auto 7|Perfil Auto 8
Gui Tab, 1
Gui Add, Text, x48 y81 w111 h23 +0x200, Latência Paragon:
Gui Add, Edit, x168 y83 w88 h21
Gui Tab, 2
Gui Add, Edit, x243 y113 w120 h21

Gui Show, w444 h298, Window
Return

GuiEscape:
GuiClose:
    ExitApp

